services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - ${CADDY_HTTP_PORT:?}:80
      - ${CADDY_HTTPS_PORT:?}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy_data:/data
      - django_media:/django_media
      - django_static:/django_static
    restart: unless-stopped

  django:
    image: opengisch/django-oapif-demo:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      cache_from:
        - opengisch/django-oapif-demo:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/oapif/"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - django_static:/django_static
      - django_media:/django_media
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG:?}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL:?}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME:?}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD:?}
      DJANGO_READWRITE_USER_USERNAME: ${DJANGO_READWRITE_USER_USERNAME:?}
      DJANGO_READWRITE_USER_PASSWORD: ${DJANGO_READWRITE_USER_PASSWORD:?}
      DJANGO_READONLY_USER_USERNAME: ${DJANGO_READONLY_USER_USERNAME:?}
      DJANGO_READONLY_USER_PASSWORD: ${DJANGO_READONLY_USER_PASSWORD:?}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:?}
      DJANGO_STATIC_ROOT: /django_static
      DJANGO_MEDIA_ROOT: /django_media
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
      POSTGRES_HOST: ${POSTGRES_HOST:?}
      POSTGRES_PORT: ${POSTGRES_PORT:?}
      POSTGRES_SSLMODE: ${POSTGRES_SSLMODE:?}
      CADDY_DOMAIN: ${CADDY_DOMAIN:?}
    labels:
      caddy: ${CADDY_DOMAIN:?}
      caddy.reverse_proxy: "{{upstreams 8000}}"
      caddy.0_handle_path: /media/*
      caddy.0_handle_path.root: /django_media
      caddy.0_handle_path.file_server:
      caddy.1_handle_path: /static/*
      caddy.1_handle_path.root: /django_static
      caddy.1_handle_path.file_server:
    command: gunicorn oapif_demo.wsgi:application --bind 0.0.0.0:8000

  postgres:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
    healthcheck:
      test: psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT ST_MakePoint(0,0)'
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  caddy_data:
  django_static:
  django_media:
  postgres_data:
